### ISSUE TITLE
generation_time in ParameterValue class does not have tzinfo set properly

### ISSUE THREAD

**Issue by merose** [yamcs/python-yamcs-client#8]
The generation_time attribute in ParameterValue has tzinfo set to None. This causes the wrong interpretation when converting to a UNIX timestamp with datetime.timestamp(). I think the proper fix is to set the `tzinfo` to `timezone.utc` when creating the `datetime`.

To reproduce (on a machine where the time zone offset from UTC is nonzero):

    $ python
    Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
    [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from datetime import datetime, timezone
    >>> from yamcs.client import YamcsClient
    >>> client = YamcsClient('localhost:8090')
    >>> processor = client.get_processor(instance='viper', processor='realtime')
    >>> pv = processor.get_parameter_value('/--path-to-parameter--')
    >>> t = pv.generation_time
    >>> now = datetime.now()
    >>> now_utc = datetime.now(timezone.utc)
    >>> t
    datetime.datetime(2020, 8, 21, 20, 1, 41, 421000)
    >>> now
    datetime.datetime(2020, 8, 21, 13, 15, 21, 187699)
    >>> now_utc
    datetime.datetime(2020, 8, 21, 20, 15, 29, 413706, tzinfo=datetime.timezone.utc)

Note that the time of the parameter value is close to the current UTC time components, but its time zone is not set.

    >>> t.timestamp()
    1598065301.421
    >>> now_utc.timestamp()
    1598040929.413706

Note that getting a timestamp value now results in the parameter time adding the UTC offset, which is now almost 7 hours ahead of the current UTC time.

Workaround: copy the parameter generation time, setting the time zone at the same time

    >>> t2 = pv.generation_time.replace(tzinfo=timezone.utc)
    >>> t
    datetime.datetime(2020, 8, 21, 20, 1, 41, 421000)
    >>> t2
    datetime.datetime(2020, 8, 21, 20, 1, 41, 421000, tzinfo=datetime.timezone.utc)

Note that the original `generation_time` _t_ and the new one _t2_ have the same components, but _t2_ also has the time zone set.

    >>> t2.timestamp()
    1598040101.421
    >>> now_utc.timestamp()
    1598040929.413706

And now the timestamp is only a fraction of an hour behind the current UTC timestamp, as expected.

**Comment by fqqb** [comment]
First attempt is available from "time" branch. The changes were widespread, so it needs to settle down a bit, before going to "master" branch.

The changes also do the work to allow timezones on input to Yamcs. For example, when creating an event, a tz-aware timestamp can now be used too (it gets locally converted to UTC).

For output from Yamcs, I'm faced with the following choice:
  * Use local timezone as the default
  * Use UTC as the default

I have it on UTC for now, but I'm playing with the idea to localize by default. Either way there shall be some static configuration option that you can use to override the default.

A similar design choice needs to be made for the use case where a naive timestamp is used for querying (for example a time range request), then I have to decide whether that naive timestamp is interpreted as UTC or local. Here as well, I'm thinking local might be the better choice (then you can use ``datetime.now()`` instead of having to use ``datetime.utcnow()`` for the current time.


Let me know if you have further thoughts on any of this.

**Comment by fqqb** [comment]
On master. Returned server times are tz-aware now (defaulting to local timezone). There's an escape to make them UTC by setting the environment variable `PYTHON_YAMCS_CLIENT_UTC` to `1` (same point in time).

For the other direction (client times) the client will raise an error if a naive datetime is used (previously it was assuming it to be UTC, but I think it should either be local or not-allowed).
